spring:

  redis:
    host: 127.0.0.1
    password: null
    port: 6379
    timeout: 0
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0

server:
  port: 8081
